/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthUpdatePasswordRouteImport } from './routes/auth_.update-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth_.reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConciliacaoRouteImport } from './routes/_authenticated/conciliacao'
import { Route as AuthenticatedConciliacaoIndexRouteImport } from './routes/_authenticated/conciliacao.index'
import { Route as AuthenticatedConfiguracoesUsuariosRouteImport } from './routes/_authenticated/configuracoes.usuarios'
import { Route as AuthenticatedConfiguracoesContasRouteImport } from './routes/_authenticated/configuracoes.contas'
import { Route as AuthenticatedConciliacaoNovaRouteImport } from './routes/_authenticated/conciliacao.nova'
import { Route as AuthenticatedConciliacaoMassaRouteImport } from './routes/_authenticated/conciliacao.massa'
import { Route as AuthenticatedConciliacaoFilaRouteImport } from './routes/_authenticated/conciliacao.fila'
import { Route as AuthenticatedConciliacaoIdRouteImport } from './routes/_authenticated/conciliacao.$id'
import { Route as AuthenticatedConciliacaoContaAccountIdRouteImport } from './routes/_authenticated/conciliacao.conta.$accountId'
import { Route as AuthenticatedConciliacaoIdVinculosRouteImport } from './routes/_authenticated/conciliacao.$id_.vinculos'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUpdatePasswordRoute = AuthUpdatePasswordRouteImport.update({
  id: '/auth_/update-password',
  path: '/auth/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth_/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConciliacaoRoute =
  AuthenticatedConciliacaoRouteImport.update({
    id: '/conciliacao',
    path: '/conciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConciliacaoIndexRoute =
  AuthenticatedConciliacaoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConciliacaoRoute,
  } as any)
const AuthenticatedConfiguracoesUsuariosRoute =
  AuthenticatedConfiguracoesUsuariosRouteImport.update({
    id: '/configuracoes/usuarios',
    path: '/configuracoes/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesContasRoute =
  AuthenticatedConfiguracoesContasRouteImport.update({
    id: '/configuracoes/contas',
    path: '/configuracoes/contas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConciliacaoNovaRoute =
  AuthenticatedConciliacaoNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedConciliacaoRoute,
  } as any)
const AuthenticatedConciliacaoMassaRoute =
  AuthenticatedConciliacaoMassaRouteImport.update({
    id: '/massa',
    path: '/massa',
    getParentRoute: () => AuthenticatedConciliacaoRoute,
  } as any)
const AuthenticatedConciliacaoFilaRoute =
  AuthenticatedConciliacaoFilaRouteImport.update({
    id: '/fila',
    path: '/fila',
    getParentRoute: () => AuthenticatedConciliacaoRoute,
  } as any)
const AuthenticatedConciliacaoIdRoute =
  AuthenticatedConciliacaoIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedConciliacaoRoute,
  } as any)
const AuthenticatedConciliacaoContaAccountIdRoute =
  AuthenticatedConciliacaoContaAccountIdRouteImport.update({
    id: '/conta/$accountId',
    path: '/conta/$accountId',
    getParentRoute: () => AuthenticatedConciliacaoRoute,
  } as any)
const AuthenticatedConciliacaoIdVinculosRoute =
  AuthenticatedConciliacaoIdVinculosRouteImport.update({
    id: '/$id_/vinculos',
    path: '/$id/vinculos',
    getParentRoute: () => AuthenticatedConciliacaoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conciliacao': typeof AuthenticatedConciliacaoRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/conciliacao/$id': typeof AuthenticatedConciliacaoIdRoute
  '/conciliacao/fila': typeof AuthenticatedConciliacaoFilaRoute
  '/conciliacao/massa': typeof AuthenticatedConciliacaoMassaRoute
  '/conciliacao/nova': typeof AuthenticatedConciliacaoNovaRoute
  '/configuracoes/contas': typeof AuthenticatedConfiguracoesContasRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/conciliacao/': typeof AuthenticatedConciliacaoIndexRoute
  '/conciliacao/$id/vinculos': typeof AuthenticatedConciliacaoIdVinculosRoute
  '/conciliacao/conta/$accountId': typeof AuthenticatedConciliacaoContaAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/update-password': typeof AuthUpdatePasswordRoute
  '/conciliacao/$id': typeof AuthenticatedConciliacaoIdRoute
  '/conciliacao/fila': typeof AuthenticatedConciliacaoFilaRoute
  '/conciliacao/massa': typeof AuthenticatedConciliacaoMassaRoute
  '/conciliacao/nova': typeof AuthenticatedConciliacaoNovaRoute
  '/configuracoes/contas': typeof AuthenticatedConfiguracoesContasRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/conciliacao': typeof AuthenticatedConciliacaoIndexRoute
  '/conciliacao/$id/vinculos': typeof AuthenticatedConciliacaoIdVinculosRoute
  '/conciliacao/conta/$accountId': typeof AuthenticatedConciliacaoContaAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/conciliacao': typeof AuthenticatedConciliacaoRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth_/reset-password': typeof AuthResetPasswordRoute
  '/auth_/update-password': typeof AuthUpdatePasswordRoute
  '/_authenticated/conciliacao/$id': typeof AuthenticatedConciliacaoIdRoute
  '/_authenticated/conciliacao/fila': typeof AuthenticatedConciliacaoFilaRoute
  '/_authenticated/conciliacao/massa': typeof AuthenticatedConciliacaoMassaRoute
  '/_authenticated/conciliacao/nova': typeof AuthenticatedConciliacaoNovaRoute
  '/_authenticated/configuracoes/contas': typeof AuthenticatedConfiguracoesContasRoute
  '/_authenticated/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/_authenticated/conciliacao/': typeof AuthenticatedConciliacaoIndexRoute
  '/_authenticated/conciliacao/$id_/vinculos': typeof AuthenticatedConciliacaoIdVinculosRoute
  '/_authenticated/conciliacao/conta/$accountId': typeof AuthenticatedConciliacaoContaAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/conciliacao'
    | '/dashboard'
    | '/auth/reset-password'
    | '/auth/update-password'
    | '/conciliacao/$id'
    | '/conciliacao/fila'
    | '/conciliacao/massa'
    | '/conciliacao/nova'
    | '/configuracoes/contas'
    | '/configuracoes/usuarios'
    | '/conciliacao/'
    | '/conciliacao/$id/vinculos'
    | '/conciliacao/conta/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/reset-password'
    | '/auth/update-password'
    | '/conciliacao/$id'
    | '/conciliacao/fila'
    | '/conciliacao/massa'
    | '/conciliacao/nova'
    | '/configuracoes/contas'
    | '/configuracoes/usuarios'
    | '/conciliacao'
    | '/conciliacao/$id/vinculos'
    | '/conciliacao/conta/$accountId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/conciliacao'
    | '/_authenticated/dashboard'
    | '/auth_/reset-password'
    | '/auth_/update-password'
    | '/_authenticated/conciliacao/$id'
    | '/_authenticated/conciliacao/fila'
    | '/_authenticated/conciliacao/massa'
    | '/_authenticated/conciliacao/nova'
    | '/_authenticated/configuracoes/contas'
    | '/_authenticated/configuracoes/usuarios'
    | '/_authenticated/conciliacao/'
    | '/_authenticated/conciliacao/$id_/vinculos'
    | '/_authenticated/conciliacao/conta/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthUpdatePasswordRoute: typeof AuthUpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/update-password': {
      id: '/auth_/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof AuthUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/reset-password': {
      id: '/auth_/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conciliacao': {
      id: '/_authenticated/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof AuthenticatedConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conciliacao/': {
      id: '/_authenticated/conciliacao/'
      path: '/'
      fullPath: '/conciliacao/'
      preLoaderRoute: typeof AuthenticatedConciliacaoIndexRouteImport
      parentRoute: typeof AuthenticatedConciliacaoRoute
    }
    '/_authenticated/configuracoes/usuarios': {
      id: '/_authenticated/configuracoes/usuarios'
      path: '/configuracoes/usuarios'
      fullPath: '/configuracoes/usuarios'
      preLoaderRoute: typeof AuthenticatedConfiguracoesUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/contas': {
      id: '/_authenticated/configuracoes/contas'
      path: '/configuracoes/contas'
      fullPath: '/configuracoes/contas'
      preLoaderRoute: typeof AuthenticatedConfiguracoesContasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conciliacao/nova': {
      id: '/_authenticated/conciliacao/nova'
      path: '/nova'
      fullPath: '/conciliacao/nova'
      preLoaderRoute: typeof AuthenticatedConciliacaoNovaRouteImport
      parentRoute: typeof AuthenticatedConciliacaoRoute
    }
    '/_authenticated/conciliacao/massa': {
      id: '/_authenticated/conciliacao/massa'
      path: '/massa'
      fullPath: '/conciliacao/massa'
      preLoaderRoute: typeof AuthenticatedConciliacaoMassaRouteImport
      parentRoute: typeof AuthenticatedConciliacaoRoute
    }
    '/_authenticated/conciliacao/fila': {
      id: '/_authenticated/conciliacao/fila'
      path: '/fila'
      fullPath: '/conciliacao/fila'
      preLoaderRoute: typeof AuthenticatedConciliacaoFilaRouteImport
      parentRoute: typeof AuthenticatedConciliacaoRoute
    }
    '/_authenticated/conciliacao/$id': {
      id: '/_authenticated/conciliacao/$id'
      path: '/$id'
      fullPath: '/conciliacao/$id'
      preLoaderRoute: typeof AuthenticatedConciliacaoIdRouteImport
      parentRoute: typeof AuthenticatedConciliacaoRoute
    }
    '/_authenticated/conciliacao/conta/$accountId': {
      id: '/_authenticated/conciliacao/conta/$accountId'
      path: '/conta/$accountId'
      fullPath: '/conciliacao/conta/$accountId'
      preLoaderRoute: typeof AuthenticatedConciliacaoContaAccountIdRouteImport
      parentRoute: typeof AuthenticatedConciliacaoRoute
    }
    '/_authenticated/conciliacao/$id_/vinculos': {
      id: '/_authenticated/conciliacao/$id_/vinculos'
      path: '/$id/vinculos'
      fullPath: '/conciliacao/$id/vinculos'
      preLoaderRoute: typeof AuthenticatedConciliacaoIdVinculosRouteImport
      parentRoute: typeof AuthenticatedConciliacaoRoute
    }
  }
}

interface AuthenticatedConciliacaoRouteChildren {
  AuthenticatedConciliacaoIdRoute: typeof AuthenticatedConciliacaoIdRoute
  AuthenticatedConciliacaoFilaRoute: typeof AuthenticatedConciliacaoFilaRoute
  AuthenticatedConciliacaoMassaRoute: typeof AuthenticatedConciliacaoMassaRoute
  AuthenticatedConciliacaoNovaRoute: typeof AuthenticatedConciliacaoNovaRoute
  AuthenticatedConciliacaoIndexRoute: typeof AuthenticatedConciliacaoIndexRoute
  AuthenticatedConciliacaoIdVinculosRoute: typeof AuthenticatedConciliacaoIdVinculosRoute
  AuthenticatedConciliacaoContaAccountIdRoute: typeof AuthenticatedConciliacaoContaAccountIdRoute
}

const AuthenticatedConciliacaoRouteChildren: AuthenticatedConciliacaoRouteChildren =
  {
    AuthenticatedConciliacaoIdRoute: AuthenticatedConciliacaoIdRoute,
    AuthenticatedConciliacaoFilaRoute: AuthenticatedConciliacaoFilaRoute,
    AuthenticatedConciliacaoMassaRoute: AuthenticatedConciliacaoMassaRoute,
    AuthenticatedConciliacaoNovaRoute: AuthenticatedConciliacaoNovaRoute,
    AuthenticatedConciliacaoIndexRoute: AuthenticatedConciliacaoIndexRoute,
    AuthenticatedConciliacaoIdVinculosRoute:
      AuthenticatedConciliacaoIdVinculosRoute,
    AuthenticatedConciliacaoContaAccountIdRoute:
      AuthenticatedConciliacaoContaAccountIdRoute,
  }

const AuthenticatedConciliacaoRouteWithChildren =
  AuthenticatedConciliacaoRoute._addFileChildren(
    AuthenticatedConciliacaoRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConciliacaoRoute: typeof AuthenticatedConciliacaoRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedConfiguracoesContasRoute: typeof AuthenticatedConfiguracoesContasRoute
  AuthenticatedConfiguracoesUsuariosRoute: typeof AuthenticatedConfiguracoesUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConciliacaoRoute: AuthenticatedConciliacaoRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedConfiguracoesContasRoute: AuthenticatedConfiguracoesContasRoute,
  AuthenticatedConfiguracoesUsuariosRoute:
    AuthenticatedConfiguracoesUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthUpdatePasswordRoute: AuthUpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
